### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by hulaba** [wanghao15536870732/DiseaseIdentification#1]
您好，您的这份代码没有找到图像识别有关的内容，请问可以补充一下吗？

**Comment by wanghao15536870732** [comment]
图像识别代码未开源，另作他用。具体参考自https://github.com/bochuanwu/Agricultural-Disease-Classification中keras框架搭建的RestNet50网络。期望对你有帮助。

**Comment by hulaba** [comment]
您好，想再请问一下您的开源代码中留了图像识别的接口吗？以及你们图像识别的代码是本地运行还是上云了？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"YyrWang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月5日(星期四) 下午5:35
收件人:&nbsp;"wanghao15536870732/DiseaseIdentification"<DiseaseIdentification@noreply.github.com&gt;;
抄送:&nbsp;"又双叒叕"<1325153037@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [wanghao15536870732/DiseaseIdentification] 问题 (#1)




图像识别代码未开源，另作他用。具体参考自https://github.com/bochuanwu/Agricultural-Disease-Classification中keras框架搭建的RestNet50网络。期望对你有帮助。

**Comment by wanghao15536870732** [comment]
还未完全开源。图像识别用的华为云。

**Comment by hulaba** [comment]
好的，谢谢您，祝工作顺利，这个项目进展顺利！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"YyrWang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月5日(星期四) 下午5:44
收件人:&nbsp;"wanghao15536870732/DiseaseIdentification"<DiseaseIdentification@noreply.github.com&gt;;
抄送:&nbsp;"又双叒叕"<1325153037@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [wanghao15536870732/DiseaseIdentification] 问题 (#1)




还未完全开源。图像识别用的华为云。
