### ISSUE TITLE
后端部分开源

### ISSUE THREAD

**Issue by GuoZiStore** [wanghao15536870732/DiseaseIdentification#3]
你好，请问后端部分可以开源用来学习吗？

**Comment by mirage208** [comment]
> 你好，请问后端部分可以开源用来学习吗？

估计是不会开源的吧

**Comment by wanghao15536870732** [comment]
+ 模型训练 https://github.com/wanghao15536870732/plants_disease_classify
+ 后端代码 https://pan.baidu.com/s/11EW65RMNbinIxoeCSr8xLw [提取码：fjqi]

后端一直并未开源的原因是小组队员协作搭建的，我了解并不多，他也并未开源（有些冗余），最新的代码可能丢失了，暂时只找到一份早期的代码。非常抱歉！

**Comment by mirage208** [comment]
谢谢
